// <auto-generated />
using System;
using BFF.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BFF.Context.Migrations
{
    [DbContext(typeof(BffDbContext))]
    partial class BffDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BFF.Models.Entities.AccessGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("PermissionMask")
                        .HasColumnType("integer")
                        .HasColumnName("permission_mask");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid")
                        .HasColumnName("principal_id");

                    b.Property<short>("PrincipalType")
                        .HasColumnType("smallint")
                        .HasColumnName("principal_type");

                    b.Property<int>("ResourceId")
                        .HasColumnType("integer")
                        .HasColumnName("resource_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_access_grants");

                    b.HasIndex("ResourceId");

                    b.HasIndex("PrincipalType", "PrincipalId")
                        .HasDatabaseName("ix_access_grants_principal");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("PrincipalType", "PrincipalId"), new[] { "ResourceId", "PermissionMask" });

                    b.HasIndex("PrincipalType", "PrincipalId", "ResourceId")
                        .IsUnique()
                        .HasDatabaseName("ux_access_grants_principal_resource");

                    b.ToTable("access_grants", null, t =>
                        {
                            t.HasCheckConstraint("ck_access_grants_principal_type", "principal_type IN (1,2)");
                        });
                });

            modelBuilder.Entity("BFF.Models.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_groups");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_groups_code");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("BFF.Models.Entities.GroupClosure", b =>
                {
                    b.Property<Guid>("AncestorId")
                        .HasColumnType("uuid")
                        .HasColumnName("ancestor_id");

                    b.Property<Guid>("DescendantId")
                        .HasColumnType("uuid")
                        .HasColumnName("descendant_id");

                    b.Property<int>("Depth")
                        .HasColumnType("integer")
                        .HasColumnName("depth");

                    b.HasKey("AncestorId", "DescendantId")
                        .HasName("pk_group_closure");

                    b.HasIndex("DescendantId", "AncestorId")
                        .HasDatabaseName("ix_group_closure_descendant_ancestor");

                    b.ToTable("group_closure", (string)null);
                });

            modelBuilder.Entity("BFF.Models.Entities.GroupMember", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<short>("MemberType")
                        .HasColumnType("smallint")
                        .HasColumnName("member_type");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("GroupId", "MemberType", "MemberId")
                        .HasName("pk_group_members");

                    b.HasIndex("MemberType", "MemberId")
                        .HasDatabaseName("ix_group_members_member");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("MemberType", "MemberId"), new[] { "GroupId" });

                    b.ToTable("group_members", null, t =>
                        {
                            t.HasCheckConstraint("ck_group_members_member_type", "member_type IN (1,2)");

                            t.HasCheckConstraint("ck_group_members_no_self_loop", "member_type <> 2 OR member_id <> group_id");
                        });
                });

            modelBuilder.Entity("BFF.Models.Entities.RbacVersion", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<long>("Value")
                        .HasColumnType("bigint")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_rbac_version");

                    b.ToTable("rbac_version", null, t =>
                        {
                            t.HasCheckConstraint("ck_rbac_version_singleton", "id = 1");
                        });
                });

            modelBuilder.Entity("BFF.Models.Entities.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_resources");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_resources_code");

                    b.ToTable("resources", (string)null);
                });

            modelBuilder.Entity("BFF.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auth_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text")
                        .HasColumnName("middle_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("AuthUserId")
                        .IsUnique()
                        .HasDatabaseName("ux_users_auth_user_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("BFF.Models.Entities.AccessGrant", b =>
                {
                    b.HasOne("BFF.Models.Entities.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_access_grants_resources");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("BFF.Models.Entities.GroupClosure", b =>
                {
                    b.HasOne("BFF.Models.Entities.Group", null)
                        .WithMany()
                        .HasForeignKey("AncestorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_closure_ancestor");

                    b.HasOne("BFF.Models.Entities.Group", null)
                        .WithMany()
                        .HasForeignKey("DescendantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_closure_descendant");
                });

            modelBuilder.Entity("BFF.Models.Entities.GroupMember", b =>
                {
                    b.HasOne("BFF.Models.Entities.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_members_groups");
                });
#pragma warning restore 612, 618
        }
    }
}
